[project]
name = "commons-clipper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ffmpeg>=1.4",
    "requests>=2.32.5",
    "rich>=14.2.0",
]
